# Generated by Django 2.2.14 on 2022-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='nombre_prueba',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
