# Generated by Django 2.2.14 on 2022-11-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_remove_prueba_nombre_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
