# Generated by Django 2.2.14 on 2022-11-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=45, null=True)),
                ('estado', models.CharField(max_length=45, null=True)),
                ('grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, null=True, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('usuario', models.CharField(max_length=45, null=True)),
                ('fecha_de_registro', models.DateField()),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Estudiante')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'verbose_name': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.TipoDocumento'),
        ),
    ]
