# Generated by Django 2.2.14 on 2022-11-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=225, null=True)),
                ('pregunta', models.CharField(max_length=45, null=True, verbose_name='Preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_resultado', models.CharField(max_length=45, null=True)),
                ('retroalimentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bancoPregunta.Retroalimentacion')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaBancoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bancoPregunta.BancoPregunta')),
            ],
        ),
    ]
