# Generated by Django 2.2.14 on 2022-12-07 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
        ('profiles', '0001_initial'),
        ('prueba', '0001_initial'),
        ('bancoPregunta', '0002_auto_20221206_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Estudiante'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bancoPregunta.Resultado'),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.Estado'),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Grado'),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Materia'),
        ),
    ]
