# Generated by Django 2.2.14 on 2022-11-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoPregunta', '0002_auto_20221118_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroalimentacion',
            name='nombre',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
